routingPanier:
    resource: "@EcommerceBundle/Resources/config/routing/routingPannier.yml"
    prefix: /panier
    
routingProduits:
    resource: "@EcommerceBundle/Resources/config/routing/routingProduits.yml"
    prefix: /
        
test:
    pattern:  /test
    defaults: { _controller: EcommerceBundle:Test:testFormulaire }