parameters:
#    ecommerce.example.class: Ecommerce\EcommerceBundle\Example

services:
#    ecommerce.example:
#        class: %ecommerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    tva:
        class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension }
